### ISSUE TITLE
Generated code are checked in to repository

### ISSUE THREAD

**Issue by helloworld1** [linkedin/dagli#1]
In the examples, e.g. fasttext-and-avro, the generated code is checked into the repository. The common practice is not checking in generated code. Would it be possible to configure the build so the code is generated in the `build` directory instead of the `src` directory? This will make the source cleaner and avoid the generated code to be checked in to repository.

**Comment by jeffpasternack** [comment]
Hi Howard, thanks for reporting this.  It looks like our .gitignore didn't cover these directories, so we'll fix that and remove them shortly.  Incidentally, elsewhere in the project we do (intentionally) check in code generated from FreeMarker; we'd like to avoid that too, if we could, but that will need to wait until an appropriate Gradle plugin becomes available.

**Comment by jeffpasternack** [comment]
Fixed: https://github.com/linkedin/dagli/commit/2edf4673a254302e06e1b7423149010565ec013a
