### ISSUE TITLE
Get XGBoostClassification.Prepared has no "asLeafFeatures()" method

### ISSUE THREAD

**Issue by cyberbeat** [linkedin/dagli#4]
I intensivly trained a XGBoostClassification model and saved the prepared DAG instance to a file.

Now, after loading the model from file, I like to examine some examples with the "asLeafFeatures" Producer, but I see no possibility without the XGBoostClassification instance. I only find the ""XGBoostClassification.Prepared" instance in the prepared model. Would it be possible to add these methods also to the Prepared instance?

**Comment by jeffpasternack** [comment]
Typically, the way you'd do this is by creating your DAG as something like this:

>   XGBoostClassification<L> classification = new XGBoostClassification<L>(...);
>   Producer<Vector> leafVector = classification.asLeafFeatures();
>   DAG1x2<X, Vector, L> preparableDAG = DAG.withPlaceholder(someExamplePlaceholder).withOutputs(leafVector, classification);
>   DAG1x2.Prepared<X, Vector, L> preparedDAG = preparableDAG.prepare(...);

Then you can get a vector corresponding to the leaves by invoking:
>  Vector leafVector = preparedDAG.apply(someExample).get0();

I'm assuming you also care about the label predicted by the XGBoost model, too, in addition to the leaves.  Once you have this prepared DAG, incidentally, you can pare it down if you only care about a subset of the outputs:
>  DAG1x1<X, Vector> preparedLeafVectorDAG = DAG.Prepared.withPlaceholder(someExamplePlaceholder).withOutput(new Value0FromTuple<>(preparedDAG);

It's also possible, of course, to get an XGBoost Booster object out of the `XGBoostClassification.Prepared` instance by calling `getBooster()` and using the "XGBoost-native" methods on it, but this is not the method we'd recommend.

**Comment by cyberbeat** [comment]
Thanks, closing this.
